### PR TITLE
Add single-node MPI instructions

### PR DESCRIPTION
**Pull request by fsimonis**
This PR adds instructions on how to run MPI programs on a single node

### CODE REVIEW

**Review by uekerman — APPROVED** [review]
Good to have such things documented :+1:
I am still a bit puzzled on how this pinning is different from the pinning explained on the `running-distributed` page. Why could the pinning there not be used on a single node?

**Comment by uekerman** [comment]
A link back from `running-distributed` to here could also help.

**Comment by fsimonis** [comment]
@uekerman 

"Running locally" is about running the simulation locally aka on one node. We need to pin CPUs here.

"Running distributed" is about running across machines. This doesn't necessarily mean MPI. It could mean one participant runs locally on my laptop and one runs on my cluster. Or both run in separate containers.

"Running SLURM" is about running on a cluster. Here we need to distribute whole nodes allocated to the job across multiple participants.

> A link back from running-distributed to here could also help.

The entire section is kind of meant to be read linearly, right?
Where would you mention it?

**Comment by uekerman** [comment]
> Where would you mention it?

Maybe a hint below https://precice.org/running-slurm.html#running-partitioned-simulations that one you could also use the "running local" pinning mechanism? Or briefly explain there how both differ.

> The entire section is kind of meant to be read linearly, right?

I don't think that we can expect this anywhere in our documentation. Users follow links or search and then end up on any page.

**Pull request merged**
