### PR TITLE
Simplify the SLURM hostfile setup

### PR DESCRIPTION
**Pull request by fsimonis**
This PR simplifies the SLURM explanation.
Hostfiles are now generated using slot notations.
This allows to run mpi without `-n` as it scales to all available slots.

The hostfiles now don't contain repeated hosts, as repeating hosts could still lead to double allocation of CPUs on nodes that used by multiple hostfiles.

@davidscn could you test these formats on the AMD cluster?

I also created a python version of the script to generate hostfiles for an active SLURM session. Is this actually useful, or is it easier to code the generation into the bash of the SLURM jobs? If it is useful, where should it go? In a gist, added to the website as a file, added as text, or added to a separate repo in the org?
https://gist.github.com/fsimonis/4e312c3875c276d96f358bb0ff8ce7a2

### CODE REVIEW

**Comment by fsimonis** [comment]
Merging now as it's definitely an improvement.

**Comment by uekerman** [comment]
>  In a gist, added to the website as a file, added as text, or added to a separate repo in the org?

Do you link to the gist from the website? That would be good already.

**Comment by fsimonis** [comment]
No, the gist is still completely separate until we know where to put it.

**Comment by uekerman** [comment]
I used to code the generation in the SLURM bash files, but I still think that this could be useful. Simply linking to the gist from the website is enough in my opinion. If we don't do it now, it will get lost :grin:

**Comment by fsimonis** [comment]
> If we don't do it now, it will get lost 😁

Good point

A valuable addition for the script could be the automatic detection of the MPI implementation.

That would be tedious in bash.

**Comment by fsimonis** [comment]
@uekerman Done https://github.com/precice/precice.github.io/commit/0f39d2a88d779f8e28de1db9c37816593507bc1f

**Pull request merged**
