### PR TITLE
Community Story for the preCICE page

### PR DESCRIPTION
**Pull request by JulianSchliessus**

### CODE REVIEW

**Review by MakisH — APPROVED** [review]
Nice, thank you very much, @JulianSchliessus! :hugs:

**Review by MakisH — CHANGES_REQUESTED** [review]
Actually, it looks like it does not render correctly at the moment:

Screenshot from 2022-03-22 14-53-58

I guess one issue is that we don't support multiple authors. @chlorenz is this something we could easily add? In any case, @JulianSchliessus see how the `Coupling mechanics and electrophysiology in skeletal muscles` is implemented.

The image also seems to not work. Is it referenced?

**Comment by JulianSchliessus** [comment]
Thanks for the information :grinning:.
I have changed the filename of the image and merged the author names into one block.

**Review by MakisH — APPROVED** [review]
Now it looks fine, thanks a lot for the quick reaction!

**Pull request merged**
