### PR TITLE
Simplify notes and versions

### PR DESCRIPTION
**Pull request by fsimonis**
This PR adds Liquid blocks for notes, warnings, tips, disclaimers and version information.

This simplifies writing notes etc to more natural syntax:

```liquid
{% note %}
This is my note.
{% endnote %}
```
_note: the icons don't render locally for some reason_
image
image

I will migrate adapter notes once this PR is merged.

### CODE REVIEW

**Comment by fsimonis** [comment]
After a discussion with @uekerman, I replaced the `version_since` tag with a `version` block.
This allows to enter free text, which covers more use-cases.
I updated the images in the PR.

**Comment by MakisH** [comment]
I tried building locally, but I get a related error even in a clean copy of the repository. Do I maybe need a newer version of Jekyll? In any case, we should document it.

```
$ bundle exec jekyll serve --safe -l
Configuration file: /home/makish/Desktop/precice.github.io/_config.yml
            Source: /home/makish/Desktop/precice.github.io
       Destination: /home/makish/Desktop/precice.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 1): Unknown tag 'warning' in pages/docs/adapters/calculix/adapter-calculix-supermuc.md
                    ------------------------------------------------
      Jekyll 4.1.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
```

I am using Jekyll 4.1.1, Ruby 2.7.0, on Ubuntu 21.10.

Note that we don't have a website build check here. (related to #107)

**Comment by fsimonis** [comment]
@MakisH We don't use the jekyll safe mode since we incorporated the tutorials.
Its disables custom plugins, hence the missing tag.

**Comment by MakisH** [comment]
> @MakisH We don't use the jekyll safe mode since we incorporated the tutorials. Its disables custom plugins, hence the missing tag.

Right, I had a feeling that we changed that at some point. Can you please also update the README, then?

**Comment by fsimonis** [comment]
@MakisH Right. I fixed it directly on master https://github.com/precice/precice.github.io/commit/b0639edb5dba51aaf0fce9ae628b7b8ffa2bae11

**Comment by chlorenz** [comment]
Nice work @fsimonis !

I've added a whitespace after the icon for the version blocks in https://github.com/precice/precice.github.io/commit/7086a22f91838ab9dc76071b6998230d7b14e0c9.

**Pull request merged**
