### PR TITLE
Redo FEniCS-preCICE adapter handling of literature

### PR DESCRIPTION
**Pull request by ajaust**
This PR cleans up the way the FEniCS-preCICE adapter's documentation handles literature. 

## Main changes

- Updated style of references to be consistent with the reference list of homepage
- Generate the reference lists automatically from the publication list of this homepage. I added some extra fields for publications (for the Rodenberg2021 and Hertrich2019 publication) which allow for easier sorting literature-dependent formatting. For example, the output of a Bachelor's thesis looks different than for a journal paper.
- Remove hard coded links within the text, e.g., 'see [1]'" ../../pages/docs/adapters/fenics/adapter-fenics.md
- Added a `bib` file for the FEniCS-preCICE adapter.

## Current issues (I am aware of)

- The appearance of the FEniCS-preCICE adapter's literature box on the adapter page now differs from the appearance on the general "Publictions" page of the preCICE homepage.
- Is the addition of fields for the literature ok? I added some (and already abuse the notation slightly) for the added fiels. 

## Further notes

This PR replaces #96.

### CODE REVIEW

**Comment by ajaust** [comment]
@BenjaminRodenberg I think I would need feedback from you and someone who is responsible for the homepage design whether the addition of fields in publications is acceptable (for the moment) or whether one wants to set this up differently.

**Review by BenjaminRodenberg — APPROVED** [review]
I had a quick look at the details and it is definitely a big improvement compared to the current state. About the website styling and policies I cannot give a comprehensive review. @MakisH could you have a brief look here?

If there are bigger workpackages w.r.t restructuring the documentation, I think we could also merge this PR, because it updates the (currently outdated) citing information and continue on the restructuring in a new PR.

**Comment by ajaust** [comment]
If this redo is fine, I would work on getting this merged first. Redoing parts of the homepage and how to work with citations could be done somewhere else. It would probably make sense to also take some time to build some (somewhat) consistent templates for different types of references (theses, papers, proceedings etc.)

**Comment by ajaust** [comment]
Regarding the potential redoing part the is also an issue https://github.com/precice/precice.github.io/issues/98

If this PR is approved of, I would maybe still reformat [this line](https://github.com/ajaust/precice.github.io/blob/23778593a70eac1674999c8ba184841326688a3c/pages/docs/adapters/fenics/adapter-fenics.md?plain=1#L82) such that it is easier to understand/debug.

**Comment by BenjaminRodenberg** [comment]
> Regarding the potential redoing part the is also an issue #98
> 
> If this PR is approved of, I would maybe still reformat [this line](https://github.com/ajaust/precice.github.io/blob/23778593a70eac1674999c8ba184841326688a3c/pages/docs/adapters/fenics/adapter-fenics.md?plain=1#L82) such that it is easier to understand/debug.

Ok. Then I will wait with merging here until you trigger me again, ok?

**Comment by ajaust** [comment]
I attached a screenshot how it looked for me after the changes:

2021-11-17-screenshot-precice-homepage


I added the changes to make it (a bit more) verbose. To make it properly verbose a bit more work would be needed. It is not clear to me how to ideally prevent additional space characters from popping up. These space character tend to mess up the formatting, but that should be beyond this PR.

**Comment by ajaust** [comment]
I forgot to add that this is ready to merge from my side now.

**Comment by MakisH** [comment]
This looks indeed really nice and I will definitely like to have the same in every adapter! :+1:

**Pull request merged**
