### PR TITLE
Sort adapter overview alphabetically

### PR DESCRIPTION
**Pull request by ajaust**
This sorts the lists of official and third-party adapters
alphabetically.

Solves #161

### CODE REVIEW

**Review by uekerman — APPROVED** [review]
I like. Thanks!
Could you please rebase?

**Comment by ajaust** [comment]
I just rebased it.

**Comment by MakisH** [comment]
Thanks for contributing! Previously, it was indeed pseudo-randomly sorted, with the most actively maintained adapters on top.

Two comments:
- Now, the first adapter one sees is "ANSYS Fluent", soon followed by "COMSOL Multiphysics". We should really move them to the legacy list, because this could lead to quite some false impressions and potential frustration by users.
- Not touched by this PR but seeing this now: why "(legacy) FEniCS"? Is it already named like that everywhere? I understand that FEniCS-X is not ready and marking this "legacy" gives again a false impression (potentially for the adapter).

**Comment by ajaust** [comment]
I considered "(legacy) FEniCS" still as "FEniCS" where the "legacy" is more an additional hint that it is not FEniCS-X. I agree that it is not optimal especially since the FEniCS adapter is maintened. Maybe one should remove the "legacy" and rather add a note in the comment that this refers to the "old" FEniCS versions or refer to the FEniCS-X adapter below.

**Comment by MakisH** [comment]
Now I look at it again, it is fine as it is now. :-)

**Pull request merged**
