### PR TITLE
Create 23-Strathclyde.md

### PR DESCRIPTION
**Pull request by yhuang94**
This adds a testimonial for the fluid-structure interaction modelling of flexible material wave energy converters done at University of Strathclyde. It is currently a draft as I am waiting for the final approval.

### CODE REVIEW

**Review by MakisH — APPROVED** [review]
Thank you very much for contributing! :hugs: It looks good to me.

The website builds, here is the result:

Screenshot from 2022-10-25 09-36-34

**Comment by yhuang94** [comment]
Thank you very much for merging it to the website!

**Comment by uekerman** [comment]
@yhuang94 Thanks a lot!

> Thank you very much for merging it to the website!

It is not yet merged. Is it ready from your side?

**Comment by yhuang94** [comment]
Thanks for your kind reminder. It is ready.

**Pull request merged**
